name: Testing Linters

on:
  push:

jobs:
  # static_check:
  #   name: Perform Static check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use golang ${{matrix.go-version}}
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: "^1.16"

  #     - run: go version

  #     - uses: dominikh/staticcheck-action@v1.2.0
  #       with:
  #         install-go: false

  # sec_check:
  #   name : Perform Security check
  #   runs-on: ubuntu-latest
  #   # needs: static_check
  #   env:
  #     GO111MODULE: on
  #   steps:
  #     - uses: actions/checkout@v2 
  #     - name: Run Gosec Security Scanner
  #       uses: securego/gosec@master
  #       with:
  #         args: ./...
  build:
    name: Build 
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2 

      - name: Use golang ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: '^1.6'
      - run: go version

      - name: Copy cat
        run: | 
          echo ${{secrets.TEST_NAME}} > saurav.txt
          cat saurav.txt

      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v2
      #   with:
      #     skip-go-installation: true


      # - name : Static check
      #   run: go get honnef.co/go/tools/cmd/staticcheck
      # - run: $(go env GOPATH)/bin/staticcheck ./... 

      # - name : GO security check manually
      #   run : |
      #      go get -u github.com/securego/gosec/v2/cmd/gosec
      #      go get -d

      # - run : $(go env GOPATH)/bin/gosec ./... 

