name: Testing Linters

on:
  push:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Use golang ${{matrix.go-version}}
        uses: actions/setup-go@v1
        with:
          go-version: '^1.13.1'
      - run: go version

      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v2
      #   with:
      #     skip-go-installation: true

      - name : Static check
        run: go get honnef.co/go/tools/cmd/staticcheck
      - run: $(go env GOPATH)/bin/staticcheck ./... 

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...