name: Testing Linters

on:
  push:

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env.outputs.env }}
    env:
      GITHUB_REF: ${{ github.ref }}
    steps:
      - id: get_env
        run: |
          if grep -q "refs/tags/v" <<< ${{env.GITHUB_REF}}  ||  grep -q "refs/heads/main" <<< ${{env.GITHUB_REF}}; then
            echo "::set-output name=env::Production"
          elif  grep -q "refs/heads/staging" <<< ${{env.GITHUB_REF}}; then
            echo "::set-output name=env::Staging"
          else
            echo "::set-output name=env::Development"
          fi
      - id: print_env
        name: Print environment
        run: echo  "Environment :- ${{ steps.get_env.outputs.env }}"
        
  # static_check:
  #   name: Perform Static check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use golang ${{matrix.go-version}}
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: "^1.16"

  #     - run: go version

  #     - uses: dominikh/staticcheck-action@v1.2.0
  #       with:
  #         install-go: false

  # sec_check:
  #   name : Perform Security check
  #   runs-on: ubuntu-latest
  #   # needs: static_check
  #   env:
  #     GO111MODULE: on
  #   steps:
  #     - uses: actions/checkout@v2 
  #     - name: Run Gosec Security Scanner
  #       uses: securego/gosec@master
  #       with:
  #         args: ./...
  build:
    name: Build 
    runs-on: ubuntu-latest
    needs: setup_environment
    environment: ${{needs.setup_environment.outputs.env_name}}
    steps:
      - uses: actions/checkout@v2 

      - name: Use golang ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: '^1.6'
      - run: go version

      - name: Copy cat
        run: | 
          echo ${{secrets.TEST_NAME}} > saurav.txt
          cat saurav.txt
      # - uses: stefanzweifel/git-auto-commit-action@v4          

      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v2
      #   with:
      #     skip-go-installation: true


      # - name : Static check
      #   run: go get honnef.co/go/tools/cmd/staticcheck
      # - run: $(go env GOPATH)/bin/staticcheck ./... 

      # - name : GO security check manually
      #   run : |
      #      go get -u github.com/securego/gosec/v2/cmd/gosec
      #      go get -d

      # - run : $(go env GOPATH)/bin/gosec ./... 

